apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ee-lwalliances-com
  namespace: eventengine
spec:
  secretName: ee-ingress-certs
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ee.lwalliances.com
  dnsNames:
    - ee.lwalliances.com