apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: eventengine-sa
      containers:
        - name: backend
          image: 961341558131.dkr.ecr.us-west-2.amazonaws.com/eventengine/backend:latest
          env:
            - name: eventengine_serverPort
              value: "8080"
            - name: mongo_usr
              valueFrom:
                secretKeyRef:
                  name: mongocreds
                  key: usr
            - name: mongo_pwd
              valueFrom:
                secretKeyRef:
                  name: mongocreds
                  key: pwd
            - name: mongo_host
              valueFrom:
                secretKeyRef:
                  name: mongocreds
                  key: host
            - name: eventengine_def_instance_url
              valueFrom:
                secretKeyRef:
                  name: defaultinstance
                  key: defaultLwUrl
            - name: eventengine_def_access_key_id
              valueFrom:
                secretKeyRef:
                  name: defaultinstance
                  key: defaultLwAccessKeyID
            - name: eventengine_def_secret_key
              valueFrom:
                secretKeyRef:
                  name: defaultinstance
                  key: defaultLwSecretKey
            - name: eventengine_def_sub_acct
              valueFrom:
                secretKeyRef:
                  name: defaultinstance
                  key: defaultLwSubAcct
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz/status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz/status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 80
      name: http
      targetPort: 8080
  type: LoadBalancer