apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eventengine-cluster
  region: us-west-2

vpc:
  id: vpc-0355736452e471409
  subnets:
    public:
      us-west-2a: { id: subnet-0ab5925c03ddc5dc8 }
      us-west-2b: { id: subnet-04fc5abfee8462b81 }
    private:
      us-west-2a: { id: subnet-05146055a8cdc8ebe }
      us-west-2b: { id: subnet-0d88082c94fb7b221 }

managedNodeGroups:
  - name: eventengine-nodes
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    instanceType: t2.micro