apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-west-2

vpc:
  id: vpc-0355736452e471409
  cidr: "10.0.0.0/16"
  subnets:
    private:
      private1:
        id: subnet-05146055a8cdc8ebe
      private2:
        id: subnet-0d88082c94fb7b221

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: true
    subnets:
      - private1
      - private2